// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjxlsznjeiybuzoevngc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeGxzem5qZWl5YnV6b2V2bmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDM3MDksImV4cCI6MjA3MTQxOTcwOX0.7zAlFpZwqpf0Feqbr87L6QH82E-cLwHgoYGbZmW2sHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});